version: "3.9"
services:
  client:
    container_name: Client
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      MODE: client
    ports:
      - "2202:2202"
