const  JOKE_CATEGORIES_API= 'https://api.chucknorris.io/jokes/categories';
const  SWAPI_PEOPLE_API= 'https://swapi.dev/api/people/';
const  REDIS_KEY_CHUCK_JOKE_CATEGORIES= 'chuck:joke:categories:1';
const  REDIS_KEY_SWAPI_PEOPLE= 'swapi:people:1';
const  REDIS_COMMAND_RPUSH= 'RPUSH';
const  REDIS_COMMAND_LRANGE= 'LRANGE';
const  REDIS_COMMAND_HSET= 'HSET';
const  REDIS_COMMAND_HGET= 'HGET';
const  REDIS_COMMAND_SET= 'SET';
const  REDIS_COMMAND_GET= 'GET';


module.exports = {
  JOKE_CATEGORIES_API,
  SWAPI_PEOPLE_API,
  REDIS_KEY_CHUCK_JOKE_CATEGORIES,
  REDIS_KEY_SWAPI_PEOPLE,
  REDIS_COMMAND_RPUSH,
  REDIS_COMMAND_LRANGE,
  REDIS_COMMAND_HSET,
  REDIS_COMMAND_HGET,
  REDIS_COMMAND_SET,
  REDIS_COMMAND_GET,
};
