version: "3.9"
services:
  redis:
    image: "redis"
    container_name: Cache
    ports:
      - "6379:6379"
    command: redis-server
    volumes:
      - ./data/redis:/data

  server:
    container_name: Server
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - redis
    environment:
      MODE: server
    ports:
      - "2201:2201"
